-- drop table assigns;
drop table belongs;
drop table books;
drop table rate;
-- drop table contains;
drop table items;
drop table earns;
-- drop table opens;
-- drop table provides;
-- drop table manages;
drop table ratings;
drop table processes;
drop table registers;
drop table menus;
-- drop table branch_managers;
-- drop table branches;
drop table restaurants;
drop table categories;
drop table customers;
drop table reservations;
drop table restaurant_managers;
drop table rewards;
drop table users;
